import React, { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Code2, Copy, FileText, Home, Layers3, Linkedin, Mail, Menu, Moon, Send, Sun, Volume2, VolumeX, X } from 'lucide-react';
import avatarImage from '../../assets/avatar.png';
import bbvaCover from '../../assets/359shots_so.png';
import yapeCover from '../../assets/216shots_so.png';
import allpaCover from '../../assets/344shots_so.png';

const CONTENT = {
  es: {
    nav: { profile: 'Perfil', work: 'Proyectos', capabilities: 'Capacidades', contact: 'Contacto' },
    menu: 'Abrir navegación', role: 'Product Designer & Design Engineer', location: 'Lima, Perú',
    heroEyebrow: 'PRODUCT DESIGN · FINTECH · DESIGN ENGINEERING', heroTitle: <>Rodrigo <em>Aquije</em></>,
    bio: 'Diseñador de producto digital con formación en economía. Conecto rigor analítico, sistemas de diseño escalables y conversión para construir interfaces financieras intuitivas, viables y de alto impacto.',
    bioDetail: <>Trabajo desde el problema conductual hasta la interfaz funcional: investigación, arquitectura de estados, UI, sistemas de diseño y prototipos en código. El objetivo es que una decisión compleja se sienta <strong>clara, confiable y medible.</strong></>,
    hire: 'Contactar', hireDesc: 'Cuéntame el producto, el reto y el horizonte del proyecto.', name: 'Nombre', email: 'Email', brief: 'Contexto del proyecto', send: 'Preparar mensaje', copy: 'Copiar email', copied: 'Email copiado',
    trust: 'Experiencia & colaboraciones', selected: 'Casos de estudio', workIntro: 'Tres problemas financieros abordados desde conversión, comportamiento y sistemas de interfaz.', open: 'Explorar caso completo', soon: 'Caso en desarrollo', capabilities: 'Habilidades & especialidades', connect: 'Conectemos', footer: 'Diseñado y construido en Lima.', overlayLabels: ['Rol', 'Problema', 'Contribución'],
    capabilityData: [
      { title: 'Product & Interface Design', desc: 'Investigación conductual, flujos transaccionales y arquitectura de interfaces de alta conversión.', chips: ['Figma', 'Framer', 'UX Audit', 'Prototyping'] },
      { title: 'Design Systems & Code', desc: 'Sistemas modulares escalables en Figma y componentes vivos con React y CSS Tokens.', chips: ['Design Tokens', 'React', 'HTML / CSS', 'SFMC'] },
      { title: 'AI-Augmented Prototyping', desc: 'Aceleración del prototipado funcional mediante agentes generativos sin delegar el criterio de producto.', chips: ['Codex', 'Claude Code', 'Cursor', 'Prompt-to-UI'] }
    ],
    projects: [
      { id: '01', name: 'BBVA Perú', tag: 'FINANCIAL DESIGN · SALESFORCE MC', desc: 'Optimización técnica y visual de comunicaciones masivas para BBVA Perú, manteniendo conversión e integridad regulatoria.', image: bbvaCover, href: '/casos/bbva', chips: ['Email UX', 'Compliance', 'SFMC', 'Design System'], overlay: { role: 'UX/UI & Email Design', problem: 'Una oferta variable, compleja y regulada competía por atención.', contribution: 'Jerarquía de decisión y sistema modular para campañas.' } },
      { id: '02', name: 'Yape', tag: 'BEHAVIORAL AUDIT · STATE SYSTEMS', desc: 'Rediseño conductual del estado “en revisión” para mitigar ansiedad, reintentos y abandono transaccional.', image: yapeCover, chips: ['UX Audit', 'Microcopy', 'State System'], overlay: { role: 'Behavioral UX', problem: 'La incertidumbre operativa provocaba interpretaciones y acciones equivocadas.', contribution: 'Nueva arquitectura de estado, expectativa y recuperación.' } },
      { id: '03', name: 'Allpa', tag: 'BEHAVIORAL FINANCE · APPLE ECOSYSTEM', desc: 'Concepto para Apple Watch e iOS que interviene en el flujo de caja antes de una compra impulsiva.', image: allpaCover, chips: ['watchOS', 'Behavioral Economics', 'Cash-flow UX'], overlay: { role: 'Product Concept', problem: 'La información financiera llega después de que el impulso ya ganó.', contribution: 'Intervención contextual antes del momento de gasto.' } }
    ]
  },
  en: {
    nav: { profile: 'Profile', work: 'Projects', capabilities: 'Capabilities', contact: 'Contact' },
    menu: 'Open navigation', role: 'Product Designer & Design Engineer', location: 'Lima, Peru', heroEyebrow: 'PRODUCT DESIGN · FINTECH · DESIGN ENGINEERING', heroTitle: <>Rodrigo <em>Aquije</em></>,
    bio: 'Digital product designer with an economics background. I connect analytical rigor, scalable design systems and conversion to build intuitive, viable and high-impact financial interfaces.',
    bioDetail: <>I work from the behavioral problem to the functional interface: research, state architecture, UI, design systems and code prototypes. The goal is to make complex decisions feel <strong>clear, trustworthy and measurable.</strong></>,
    hire: 'Get in touch', hireDesc: 'Share the product, the challenge and the project horizon.', name: 'Name', email: 'Email', brief: 'Project context', send: 'Prepare message', copy: 'Copy email', copied: 'Email copied',
    trust: 'Experience & collaborations', selected: 'Case studies', workIntro: 'Three financial problems approached through conversion, behavior and interface systems.', open: 'Explore full case', soon: 'Case in progress', capabilities: 'Capabilities & craft', connect: 'Let’s connect', footer: 'Designed and built in Lima.', overlayLabels: ['Role', 'Problem', 'Contribution'],
    capabilityData: [
      { title: 'Product & Interface Design', desc: 'Behavioral research, transactional flows and high-conversion interface architecture.', chips: ['Figma', 'Framer', 'UX Audit', 'Prototyping'] },
      { title: 'Design Systems & Code', desc: 'Scalable modular systems in Figma and live components with React and CSS Tokens.', chips: ['Design Tokens', 'React', 'HTML / CSS', 'SFMC'] },
      { title: 'AI-Augmented Prototyping', desc: 'Faster functional prototyping with generative agents without outsourcing product judgment.', chips: ['Codex', 'Claude Code', 'Cursor', 'Prompt-to-UI'] }
    ],
    projects: [
      { id: '01', name: 'BBVA Peru', tag: 'FINANCIAL DESIGN · SALESFORCE MC', desc: 'Technical and visual optimization of high-volume communications for BBVA Peru, balancing conversion and regulatory integrity.', image: bbvaCover, href: '/casos/bbva', chips: ['Email UX', 'Compliance', 'SFMC', 'Design System'], overlay: { role: 'UX/UI & Email Design', problem: 'A variable, complex and regulated offer competed for attention.', contribution: 'Decision hierarchy and a modular campaign system.' } },
      { id: '02', name: 'Yape', tag: 'BEHAVIORAL AUDIT · STATE SYSTEMS', desc: 'Behavioral redesign of the under-review state to reduce anxiety, retries and transactional drop-off.', image: yapeCover, chips: ['UX Audit', 'Microcopy', 'State System'], overlay: { role: 'Behavioral UX', problem: 'Operational uncertainty caused incorrect interpretations and actions.', contribution: 'A new state, expectation and recovery architecture.' } },
      { id: '03', name: 'Allpa', tag: 'BEHAVIORAL FINANCE · APPLE ECOSYSTEM', desc: 'An Apple Watch and iOS concept that intervenes in cash flow before an impulse purchase.', image: allpaCover, chips: ['watchOS', 'Behavioral Economics', 'Cash-flow UX'], overlay: { role: 'Product Concept', problem: 'Financial information arrives after the impulse has already won.', contribution: 'A contextual intervention before spending.' } }
    ]
  }
};

const CLIENTS = [['Fahrenheit DDB', 'Agency'], ['BBVA Perú', 'Banking'], ['CENTRUM PUCP', 'Business School'], ['Amsterdam Agency', 'Digital'], ['Utopiq', 'Tech']];

export default function PortfolioHome() {
  const [theme, setTheme] = useState('dark'); const [lang, setLang] = useState('es'); const [audio, setAudio] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [hireOpen, setHireOpen] = useState(false); const [active, setActive] = useState(0); const [toast, setToast] = useState(''); const [time, setTime] = useState(''); const [navTarget, setNavTarget] = useState(''); const [currentSection, setCurrentSection] = useState('profile');
  const t = CONTENT[lang]; const project = t.projects[active];
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.dataset.audio = audio ? 'on' : 'off'; document.title = 'Rodrigo Aquije — Product Designer & Design Engineer'; }, [theme, audio]);
  useEffect(() => { const tick = () => setTime(new Intl.DateTimeFormat(lang === 'es' ? 'es-PE' : 'en-US', { hour: '2-digit', minute: '2-digit', timeZone: 'America/Lima' }).format(new Date())); tick(); const timer = setInterval(tick, 30000); return () => clearInterval(timer); }, [lang]);
  useEffect(() => { if (!toast) return undefined; const timer = setTimeout(() => setToast(''), 2400); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { const nodes = document.querySelectorAll('.ref-reveal'); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .12 }); nodes.forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, []);
  useEffect(() => { const sections = document.querySelectorAll('[data-section]'); const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setCurrentSection(visible.target.dataset.section); }, { rootMargin: '-22% 0px -58% 0px', threshold: [0, .15, .4] }); sections.forEach((section) => observer.observe(section)); return () => observer.disconnect(); }, []);
  const sound = (frequency = 520, force = false) => { if (!audio && !force) return; const AudioCtx = window.AudioContext || window.webkitAudioContext; if (!AudioCtx) return; const ctx = new AudioCtx(); const oscillator = ctx.createOscillator(); const gain = ctx.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.03, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .065); oscillator.connect(gain); gain.connect(ctx.destination); oscillator.start(); oscillator.stop(ctx.currentTime + .07); };
  const selectProject = (index) => { const next = (index + t.projects.length) % t.projects.length; setActive(next); sound(440 + next * 80); };
  const notify = (message) => { setToast(message); sound(650); };
  const scrollTo = (id) => { setCurrentSection(id); setNavTarget(id); setMenuOpen(false); sound(); requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })); setTimeout(() => setNavTarget(''), 850); };
  const openProject = () => project.href ? window.location.assign(project.href) : notify(t.soon);
  const copyEmail = async () => { await navigator.clipboard.writeText('rodrigoaq996@gmail.com'); notify(t.copied); };

  return <main className={`ref-home ref-home--editorial ${navTarget ? 'is-navigating' : ''}`} data-nav-target={navTarget || undefined}>
    <div className="ref-ambient" aria-hidden="true" />
    <div className="ref-column">
      <CommandDeck t={t} time={time} theme={theme} setTheme={setTheme} lang={lang} setLang={setLang} audio={audio} setAudio={setAudio} open={menuOpen} setOpen={setMenuOpen} scrollTo={scrollTo} sound={sound} currentSection={currentSection} />

      <section id="profile" data-section="profile" className="ref-section ref-profile ref-reveal">
        <SectionLabel code="RA—01">{t.nav.profile}</SectionLabel><span className="ref-hero-eyebrow">{t.heroEyebrow}</span><h1 className="ref-hero-title">{t.heroTitle}</h1><p className="ref-hero-role">{t.role}</p>
        <div className="ref-bio"><p>{t.bio}</p><p>{t.bioDetail}</p></div>
        <div className="ref-actions"><HireConsole t={t} open={hireOpen} setOpen={setHireOpen} sound={sound} /><button className="ref-secondary ref-press" onClick={copyEmail}><Copy size={17} /> {t.copy}</button><a className="ref-icon-button ref-press has-info-overlay" href="https://linkedin.com/in/rodrigo-aquije" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={18} /><span className="social-info-overlay"><b>LinkedIn</b><small>Rodrigo Aquije V.</small><em>Conectar <ArrowUpRight size={12} /></em></span></a></div>
      </section>

      <section className="ref-section ref-trust ref-reveal" aria-label={t.trust}><SectionLabel code="RA—02">{t.trust}</SectionLabel><div className="ref-client-strip">{CLIENTS.map(([name, type]) => <span key={name}><strong>{name}</strong><small>{type}</small></span>)}</div></section>

      <section id="projects" data-section="projects" className="ref-section ref-projects ref-reveal">
        <div className="ref-heading-row"><SectionLabel code="RA—03">{t.selected}</SectionLabel><p>{t.workIntro}</p></div>
        <div className="project-console project-console--quiet"><header className="console-topbar"><button onClick={() => selectProject(active - 1)} aria-label="Previous project"><ArrowLeft size={18} /></button><div><strong>{project.name}</strong><span>{project.id} / 0{t.projects.length}</span></div><button onClick={() => selectProject(active + 1)} aria-label="Next project"><ArrowRight size={18} /></button></header>
          <div className="console-body console-body--quiet"><ul className="project-tabs project-tabs--clean">{t.projects.map((item, index) => <li key={item.id}><ProjectTab active={index === active} onClick={() => selectProject(index)} project={item} /></li>)}</ul><div className="project-stage project-stage--editorial" key={`${lang}-${project.id}`}><div className="project-stage-copy"><span>{project.tag}</span><h2>{project.name}</h2><p>{project.desc}</p><div>{project.chips.map((chip) => <small key={chip}>{chip}</small>)}</div></div><ProjectCover project={project} label={project.href ? t.open : t.soon} labels={t.overlayLabels} onClick={openProject} /></div></div>
        </div>
      </section>

      <section id="capabilities" data-section="capabilities" className="ref-section ref-capabilities ref-reveal"><SectionLabel code="RA—04">{t.capabilities}</SectionLabel><div className="capability-list">{t.capabilityData.map((capability, index) => <article key={capability.title} className="capability-row"><span>0{index + 1}</span><div><h3>{capability.title}</h3><p>{capability.desc}</p></div><div className="capability-tags">{capability.chips.map((chip) => <small key={chip}>{chip}</small>)}</div><aside><strong>{capability.title}</strong><p>{capability.desc}</p><em>{capability.chips.join(' · ')}</em></aside></article>)}</div></section>

      <section id="contact" data-section="contact" className="ref-section ref-contact ref-reveal"><SectionLabel code="RA—05">{t.connect}</SectionLabel><h2>{lang === 'es' ? <>Conversemos sobre el <em>problema real.</em></> : <>Let’s discuss the <em>real problem.</em></>}</h2><div className="contact-links"><button onClick={copyEmail}><Mail /><span><strong>Email</strong><small>rodrigoaq996@gmail.com</small></span><ArrowUpRight /></button><a href="https://linkedin.com/in/rodrigo-aquije" target="_blank" rel="noreferrer"><Linkedin /><span><strong>LinkedIn</strong><small>Red profesional</small></span><ArrowUpRight /></a><div><FileText /><span><strong>Currículum Vitae</strong><small><a href="/cv-es.pdf">ES ↗</a><a href="/cv-en.pdf">EN ↗</a></small></span></div></div></section>

      <footer className="ref-footer"><span>© 2026 Rodrigo Aquije</span><span>{t.footer}</span><nav><a href="mailto:rodrigoaq996@gmail.com">Email</a><a href="https://linkedin.com/in/rodrigo-aquije" target="_blank" rel="noreferrer">LinkedIn</a></nav></footer>
    </div><div className={`ref-toast ${toast ? 'is-visible' : ''}`} role="status" aria-live="polite"><Check size={15} /> {toast}</div>
  </main>;
}

function CommandDeck({ t, time, theme, setTheme, lang, setLang, audio, setAudio, open, setOpen, scrollTo, sound, currentSection }) {
  const items = [['profile', t.nav.profile, <Home />], ['projects', t.nav.work, <Layers3 />], ['capabilities', t.nav.capabilities, <Code2 />], ['contact', t.nav.contact, <Mail />]];
  return <header className={`command-deck command-deck--complete ${open ? 'is-open' : ''}`}><div className="command-main"><button className="command-identity has-info-overlay" onClick={() => scrollTo('profile')}><span className="command-avatar"><img src={avatarImage} alt="Rodrigo Aquije" /></span><span><strong>Rodrigo Aquije</strong><small>{t.role}</small></span><span className="identity-info-overlay"><b>Rodrigo Aquije V.</b><small>{t.location}</small><em>Economía · FinTech · Design Engineering</em></span></button><nav className="command-direct-nav" aria-label="Primary">{items.map(([id, label]) => <button key={id} className={currentSection === id ? 'is-active' : ''} aria-current={currentSection === id ? 'page' : undefined} onClick={() => scrollTo(id)}>{label}</button>)}</nav><span className="command-time">{time} · LIMA</span><div className="command-switches"><HardwareSwitch label={audio ? 'Mute audio' : 'Unmute audio'} active={audio} onClick={() => { setAudio(!audio); if (!audio) sound(720, true); }} on={<Volume2 />} off={<VolumeX />} /><HardwareSwitch label="Toggle theme" active={theme === 'light'} onClick={() => { setTheme(theme === 'dark' ? 'light' : 'dark'); sound(); }} on={<Sun />} off={<Moon />} /><HardwareSwitch label="Toggle language" active={lang === 'en'} onClick={() => { setLang(lang === 'es' ? 'en' : 'es'); sound(); }} on={<span>EN</span>} off={<span>ES</span>} /><button className="command-menu ref-press" aria-label={t.menu} aria-expanded={open} onClick={() => { setOpen(!open); sound(460); }}>{open ? <X /> : <Menu />}</button></div></div><div className="command-panel" inert={!open ? '' : undefined}><span>NAVIGATION / SCROLL</span><nav>{items.map(([id, label, icon]) => <button key={id} className={currentSection === id ? 'is-active' : ''} aria-current={currentSection === id ? 'page' : undefined} onClick={() => scrollTo(id)}>{icon}{label}<ArrowUpRight /></button>)}</nav><div className="command-panel-footer"><span>THEME · {theme.toUpperCase()}</span><span>LANG · {lang.toUpperCase()}</span><span>AUDIO · {audio ? 'ON' : 'OFF'}</span></div></div></header>;
}

function HardwareSwitch({ label, active, onClick, on, off }) { return <button className={`hardware-switch ${active ? 'is-on' : ''}`} aria-label={label} aria-pressed={active} onClick={onClick}><i><b /></i><span>{active ? on : off}</span></button>; }
function SectionLabel({ code, children }) { return <h2 className="ref-section-label"><span>{code}</span><b>{children}</b></h2>; }
function HireConsole({ t, open, setOpen, sound }) { return <div className={`hire-console ${open ? 'is-open' : ''}`}><button className="hire-trigger ref-press" onClick={() => { setOpen(!open); sound(560); }} aria-expanded={open}><span>{t.hire}</span><ArrowRight size={17} /></button><div className="hire-panel" inert={!open ? '' : undefined}><p>{t.hireDesc}</p><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); window.location.href = `mailto:rodrigoaq996@gmail.com?subject=${encodeURIComponent(`Portfolio inquiry · ${data.get('name')}`)}&body=${encodeURIComponent(`${data.get('brief')}\n\n${data.get('email')}`)}`; }}><label>{t.name}<input name="name" required autoComplete="name" /></label><label>{t.email}<input name="email" type="email" required autoComplete="email" /></label><label>{t.brief}<textarea name="brief" required rows="4" /></label><button type="submit" className="hire-submit ref-press"><Send size={15} /> {t.send}</button></form></div></div>; }
function ProjectTab({ active, onClick, project }) { return <button className={`project-tab-clean ${active ? 'is-active' : ''}`} aria-pressed={active} onClick={onClick}><span><img src={project.image} alt="" /></span><div><strong>{project.name}</strong><small>{project.id}</small></div><aside><b>{project.overlay.role}</b><p>{project.overlay.problem}</p></aside></button>; }
function ProjectCover({ project, label, labels, onClick }) { const move = (event) => { const rect = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty('--cover-x', `${((event.clientX - rect.left) / rect.width) * 100}%`); event.currentTarget.style.setProperty('--cover-y', `${((event.clientY - rect.top) / rect.height) * 100}%`); }; return <button className="project-cover-clean ref-press" onClick={onClick} onPointerMove={move}><img src={project.image} alt={`${project.name} project cover`} /><i /><span className="cover-action">{label}<ArrowUpRight size={15} /></span><div className="cover-info-overlay"><span><small>{labels[0]}</small><b>{project.overlay.role}</b></span><span><small>{labels[1]}</small><b>{project.overlay.problem}</b></span><span><small>{labels[2]}</small><b>{project.overlay.contribution}</b></span></div></button>; }
